#!/bin/bash

# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

JAVA_HOME="/usr/share/carbonio:/opt/zextras/common/lib/jvm/java"
export JAVA_HOME
/opt/zextras/common/bin/java \
  -Djava.net.preferIPv4Stack=true \
  -Xmx1024m \
  -Xms1024m \
  -DTASKS_LOG_LEVEL=warn \
  -jar /usr/share/carbonio/carbonio-tasks.jar
