#!/bin/bash

# SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

# Decrypt the bootstrap token, asking the password to the sys admin
# --setup checks for SETUP_CONSUL_TOKEN env variable and uses it
# to avoid re-asking for the password
echo -n "Insert the cluster credential password: "
export SETUP_CONSUL_TOKEN=$(service-discover bootstrap-token --setup)
EXIT_CODE="$?"
echo ""
if [[ "${EXIT_CODE}" != "0" ]]; then
  echo "Cannot access to bootstrap token"
  exit 1;
fi

# Standard setup via quarkus-extensions (policy, token, KV migration, systemd override)
/usr/share/carbonio/carbonio-tasks-ce-runner \
  --setup http://127.0.0.1:8500

# Limit secret visibility as much as possible
export -n SETUP_CONSUL_TOKEN

consul reload

systemctl restart carbonio-tasks.service
systemctl restart carbonio-tasks-sidecar.service
