#!/bin/bash

# SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

exec /usr/share/carbonio/carbonio-tasks-ce-runner \
  -Djava.net.preferIPv4Stack=true
